### ISSUE TITLE
Unable to Download through Atom GUI

### ISSUE THREAD

**Issue by 8bit-echo** [objectivecosta/atom-language-swift#1]
When installing through Atom's GUI package manager, application throws error:

Installing “language-swift3@0.5.1” failed.
Unable to download https://www.atom.io/api/packages/language-swift3/versions/0.5.1/tarball: 400 Bad Request Repository inaccessible.

**Comment by bygri** [comment]
For anyone unfamiliar with manual package installation, you can still install by downloading and extracting the ZIP of this repository into `~/.atom/packages/`

**Comment by martin-spa** [comment]
+1 with the same issue, installing via Atom's GUI is not working.

**Comment by 8bit-echo** [comment]
i'll check this out.   
  

  
  

  
  
>
